#!/system/bin/sh

set -eu
[ -n "${BASH_VERSION:-}" ] && set -o pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
ADDRSYNCD_BIN="${ADDRSYNCD_BIN:-${SCRIPT_DIR}/addrsyncd}"
WORK_DIR="${WORK_DIR:-${SCRIPT_DIR}}"
CONFIG_FILE="${CONFIG_FILE:-${SCRIPT_DIR}/addrsyncd.toml}"
LOG_FILE="${LOG_FILE:-${WORK_DIR}/addrsyncd.log}"
DURATION_SEC="${DURATION_SEC:-60}"
SAMPLE_SEC="${SAMPLE_SEC:-2}"
BASELINE_FILE="${BASELINE_FILE:-${SCRIPT_DIR}/docs/baseline-android.env}"
BASELINE_MD_FILE="${BASELINE_MD_FILE:-${SCRIPT_DIR}/docs/baseline-android.md}"
RECORD_BASELINE="${RECORD_BASELINE:-0}"
MAX_CPU_TICKS_DELTA="${MAX_CPU_TICKS_DELTA:-}"
MAX_EVENT_DROP="${MAX_EVENT_DROP:-}"
MAX_COMPENSATE_RESYNC="${MAX_COMPENSATE_RESYNC:-}"

fail() {
    echo "bench_failed reason=$*" >&2
    exit 1
}

is_uint() {
    case "$1" in
        ''|*[!0-9]*)
            return 1
            ;;
        *)
            return 0
            ;;
    esac
}

load_thresholds() {
    if [ -f "${BASELINE_FILE}" ]; then
        # shellcheck disable=SC1090
        . "${BASELINE_FILE}"
    fi

    if [ "${RECORD_BASELINE}" != "1" ]; then
        captured_at="${BASELINE_CAPTURED_AT:-UNSET}"
        if [ -z "${captured_at}" ] || [ "${captured_at}" = "UNSET" ]; then
            fail "baseline placeholder detected; run RECORD_BASELINE=1 sh ./bench_android.sh on Android device"
        fi
    fi

    [ -n "${MAX_CPU_TICKS_DELTA}" ] || MAX_CPU_TICKS_DELTA="${BASELINE_MAX_CPU_TICKS_DELTA:-}"
    [ -n "${MAX_EVENT_DROP}" ] || MAX_EVENT_DROP="${BASELINE_MAX_EVENT_DROP:-}"
    [ -n "${MAX_COMPENSATE_RESYNC}" ] || MAX_COMPENSATE_RESYNC="${BASELINE_MAX_COMPENSATE_RESYNC:-}"

    [ -n "${MAX_CPU_TICKS_DELTA}" ] || fail "missing MAX_CPU_TICKS_DELTA (set env or ${BASELINE_FILE})"
    [ -n "${MAX_EVENT_DROP}" ] || fail "missing MAX_EVENT_DROP (set env or ${BASELINE_FILE})"
    [ -n "${MAX_COMPENSATE_RESYNC}" ] || fail "missing MAX_COMPENSATE_RESYNC (set env or ${BASELINE_FILE})"

    is_uint "${MAX_CPU_TICKS_DELTA}" || fail "MAX_CPU_TICKS_DELTA must be unsigned integer"
    is_uint "${MAX_EVENT_DROP}" || fail "MAX_EVENT_DROP must be unsigned integer"
    is_uint "${MAX_COMPENSATE_RESYNC}" || fail "MAX_COMPENSATE_RESYNC must be unsigned integer"
}

status_text() {
    "${ADDRSYNCD_BIN}" -c "${CONFIG_FILE}" -d "${WORK_DIR}" status 2>&1 || true
}

current_pid() {
    s="$(status_text)"
    echo "${s}" | sed -n 's/^running pid=\([0-9][0-9]*\)$/\1/p'
}

count_event_delta() {
    start_line="$1"
    event="$2"
    [ -f "${LOG_FILE}" ] || {
        echo 0
        return 0
    }

    awk -v start="${start_line}" -v event="${event}" '
        NR > start && index($0, " " event " ") > 0 { count += 1 }
        END { print count + 0 }
    ' "${LOG_FILE}"
}

write_baseline_files() {
    cpu_ticks_delta="$1"
    log_lines_delta="$2"
    count_rule_batch="$3"
    count_event_drop="$4"
    count_comp_resync="$5"

    captured_at="$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date)"
    kernel="$(uname -r 2>/dev/null || echo unknown)"
    device="$(getprop ro.product.model 2>/dev/null || uname -n 2>/dev/null || echo unknown)"

    cpu_gate=$((cpu_ticks_delta + cpu_ticks_delta / 5))
    [ "${cpu_gate}" -gt 0 ] || cpu_gate=1

    mkdir -p "$(dirname "${BASELINE_FILE}")"
    cat > "${BASELINE_FILE}" <<EOF
# Auto-generated by bench_android.sh (RECORD_BASELINE=1)
# captured_at=${captured_at}
BASELINE_CAPTURED_AT=${captured_at}
BASELINE_DURATION_SEC=${DURATION_SEC}
BASELINE_SAMPLE_SEC=${SAMPLE_SEC}
BASELINE_CPU_TICKS_DELTA=${cpu_ticks_delta}
BASELINE_LOG_LINES_DELTA=${log_lines_delta}
BASELINE_COUNT_RULE_BATCH=${count_rule_batch}
BASELINE_COUNT_EVENT_DROP=${count_event_drop}
BASELINE_COUNT_COMPENSATE_RESYNC=${count_comp_resync}
BASELINE_MAX_CPU_TICKS_DELTA=${cpu_gate}
BASELINE_MAX_EVENT_DROP=0
BASELINE_MAX_COMPENSATE_RESYNC=0
EOF

    mkdir -p "$(dirname "${BASELINE_MD_FILE}")"
    cat > "${BASELINE_MD_FILE}" <<EOF
# Android Baseline (aarch64-linux-android)

This file is generated by \`bench_android.sh\` with \`RECORD_BASELINE=1\`.

## Environment

- target: \`aarch64-linux-android\`
- kernel contract: \`>= 5.10\`
- captured_at: \`${captured_at}\`
- device: \`${device}\`
- kernel: \`${kernel}\`

## Lifecycle Baseline

- script: \`test_android.sh\`
- result: \`manual-verify\`

## Bench Baseline

- script: \`bench_android.sh\`
- duration_sec: \`${DURATION_SEC}\`
- sample_sec: \`${SAMPLE_SEC}\`

### Metrics

- cpu_ticks_delta: \`${cpu_ticks_delta}\`
- log_lines_delta: \`${log_lines_delta}\`
- count_rule_batch: \`${count_rule_batch}\`
- count_event_drop: \`${count_event_drop}\`
- count_compensate_resync: \`${count_comp_resync}\`

## Thresholds

- MAX_CPU_TICKS_DELTA: \`${cpu_gate}\`
- MAX_EVENT_DROP: \`0\`
- MAX_COMPENSATE_RESYNC: \`0\`
EOF
}

main() {
    [ -x "${ADDRSYNCD_BIN}" ] || {
        echo "binary not executable: ${ADDRSYNCD_BIN}" >&2
        exit 1
    }
    version="$("${ADDRSYNCD_BIN}" --version 2>/dev/null || true)"
    if command -v sha256sum >/dev/null 2>&1; then
        digest="$(sha256sum "${ADDRSYNCD_BIN}" | awk '{print $1}')"
    else
        digest="unknown"
    fi

    pid="$(current_pid)"
    [ -n "${pid}" ] || {
        echo "daemon not running (status=$(status_text))" >&2
        exit 1
    }
    kill -0 "${pid}" 2>/dev/null || {
        echo "process not running: pid=${pid}" >&2
        exit 1
    }

    samples=$((DURATION_SEC / SAMPLE_SEC))
    [ "${samples}" -gt 0 ] || samples=1
    load_thresholds

    echo "bench_start pid=${pid} version=${version:-unknown} sha256=${digest} duration_sec=${DURATION_SEC} sample_sec=${SAMPLE_SEC}"
    start_ticks="$(awk '{print $14+$15}' "/proc/${pid}/stat" 2>/dev/null || echo 0)"
    start_log="$(wc -l < "${LOG_FILE}" 2>/dev/null || echo 0)"

    i=0
    while [ "${i}" -lt "${samples}" ]; do
        i=$((i + 1))
        now_ticks="$(awk '{print $14+$15}' "/proc/${pid}/stat" 2>/dev/null || echo 0)"
        rss_pages="$(awk '{print $24}' "/proc/${pid}/stat" 2>/dev/null || echo 0)"
        echo "sample=${i} cpu_ticks=${now_ticks} rss_pages=${rss_pages}"
        sleep "${SAMPLE_SEC}"
    done

    end_ticks="$(awk '{print $14+$15}' "/proc/${pid}/stat" 2>/dev/null || echo 0)"
    end_log="$(wc -l < "${LOG_FILE}" 2>/dev/null || echo 0)"
    tick_delta=$((end_ticks - start_ticks))
    log_delta=$((end_log - start_log))
    count_rule_batch="$(count_event_delta "${start_log}" "rule.batch")"
    count_event_drop="$(count_event_delta "${start_log}" "netlink.event_drop")"
    count_comp_resync="$(count_event_delta "${start_log}" "sync.compensate_resync")"

    echo "bench_done cpu_ticks_delta=${tick_delta} log_lines_delta=${log_delta} count_rule_batch=${count_rule_batch} count_event_drop=${count_event_drop} count_compensate_resync=${count_comp_resync}"

    if [ "${RECORD_BASELINE}" = "1" ]; then
        write_baseline_files "${tick_delta}" "${log_delta}" "${count_rule_batch}" "${count_event_drop}" "${count_comp_resync}"
        echo "baseline_written file=${BASELINE_FILE} markdown=${BASELINE_MD_FILE}"
        exit 0
    fi

    fail_reason=""
    if [ "${tick_delta}" -gt "${MAX_CPU_TICKS_DELTA}" ]; then
        fail_reason="cpu_ticks_delta(${tick_delta}>${MAX_CPU_TICKS_DELTA})"
    fi
    if [ "${count_event_drop}" -gt "${MAX_EVENT_DROP}" ]; then
        [ -n "${fail_reason}" ] && fail_reason="${fail_reason},"
        fail_reason="${fail_reason}count_event_drop(${count_event_drop}>${MAX_EVENT_DROP})"
    fi
    if [ "${count_comp_resync}" -gt "${MAX_COMPENSATE_RESYNC}" ]; then
        [ -n "${fail_reason}" ] && fail_reason="${fail_reason},"
        fail_reason="${fail_reason}count_compensate_resync(${count_comp_resync}>${MAX_COMPENSATE_RESYNC})"
    fi
    if [ -n "${fail_reason}" ]; then
        fail "${fail_reason}"
    fi
}

main "$@"
